apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: deepstream
build:
  artifacts:
    - image: ghcr.io/ahmedfawzyjr/deepstream-gateway
      context: gateway
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/ahmedfawzyjr/deepstream-inference
      context: crates/inference-engine
      docker:
        dockerfile: Dockerfile.inference
    - image: ghcr.io/ahmedfawzyjr/deepstream-api
      context: api
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infrastructure/kubernetes/base/namespace.yaml
    - infrastructure/kubernetes/base/configmap.yaml
    - infrastructure/kubernetes/base/secrets.yaml
    - infrastructure/kubernetes/base/gateway/deployment.yaml
    - infrastructure/kubernetes/base/inference/deployment.yaml
    - infrastructure/kubernetes/base/api/deployment.yaml
deploy:
  kubectl: {}
