global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'deepstream-go-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8080']

  - job_name: 'deepstream-inference'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['inference:2112']
